name: devnutri
description: Nutrition App

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.2 
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.13
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
 
